### ISSUE TITLE
Avoid repeating styles

### ISSUE THREAD

**Issue by zannain** [yipfaialan/prj-rev-bwfs-dasmoto#2]
[Dont-Repeat-Yourself](http://deviq.com/don-t-repeat-yourself/). This is an important programming principle. If you find yourself repeating certain styles this is an indication that you can simplify your stylesheet by making use of CSS classes.

Rather than [applying ](https://github.com/yipfaialan/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css#L5-L7) the following styles 5 times. 

```css
  font-family: Helvetica;
  font-size: 100px;
  font-weight: bold;
```
**Alternatives**

1. Using a `body` selector would be more appropriate

```css
body {
    font-family: Helvetica;
    font-size: 100px;
    font-weight: bold;
}
```

2.You can also create a style-specific class

```css
.bold {
   font-weight: bold;
 }
```
Now you can give multiple element tags a class attribute of `bold` and they will all receive this common style. This is in fact how CSS libraries such as [Bootstrap](https://getbootstrap.com/) work. 

3. [Using CSS Variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables)

```css
:root {
    --font-size: 1.75rem;
}

#paint {
     font-size: var(--font-size);
}
```

With any of these approaches its easy to update a style simultaneously by modifying that variable or the `.bold`/`body` selector and the entire page is updated.
